name: Python CI

on: [push]  # Run workflow on every push

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu OS

    steps:
      - uses: actions/checkout@v4  # Checkout code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest
